### ISSUE TITLE
Prototype Build and test Demonstration

### ISSUE THREAD

**Issue by jaredwhichard** [jaredwhichard/Capstone-Website#2]
Build a prototype device for Project 2. Record observations and document.
Determine next steps.

**Comment by jaredwhichard** [comment]
Started work on 11/3/2020
Spent 2 Hours trying different configurations, we were not able to connect to Arduino's website  for a time limiting us from downloading the Arduino IDE and checking their documentation.

**Comment by danielchamplain** [comment]
We were both working on this quite a bit. Jared was able to get this to work and I was still having some trouble with the Arduino. Jared is in Maine so we were working on this together but remotely.
