### ISSUE TITLE
Learn how to code on the Arduino

### ISSUE THREAD

**Issue by jaredwhichard** [jaredwhichard/Capstone-Website#4]
During this phase of the project we will be attempting to use the Arduino for ingestion. The platform is new to us and so far has been unintuitive. Our primary source for documentation will be directly from  [Arduino Tutorials](https://www.arduino.cc/en/Tutorial/HomePage) 
We will also be looking at guides for our sensor, the MAX30102 and its use in combination with Arduino.

**Comment by danielchamplain** [comment]
We have a basic understanding of how this works now.
