### ISSUE TITLE
3D Print Workstation

### ISSUE THREAD

**Issue by jaredwhichard** [jaredwhichard/Capstone-Website#5]
@danielchamplain  will be printing a workstation or mount to hold all of our devices together for prototyping. This will make is easier for us to test connections and trust that they haven't been disconnected due to movement.

**Comment by danielchamplain** [comment]
## The prototype task is complete will design one for more condensed prototype once all is working as expected.

![image](https://user-images.githubusercontent.com/60436798/98155468-48d01b80-1ea4-11eb-8f84-3f3e7df994c5.png)
